baseURL = "https://helenplatt.ca/"
languageCode = "en-us"
title = "HelenPlatt.ca"
#theme = "hugo-now-ui"

# sectionPagesMenu = "main"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"
uglyurls = true
pluralizeListTitles = false
preserveTaxonomyNames = true
paginate=36
pageinatePath="page"

[taxonomies]
  category = "categories"

[permalinks]
  post = "/:filename/"

[params]
    description = "HelenPlatt.ca Art blog and sales"
    date_format = "2006-01-02"
    tint="blue"
    background = "/img/header.png"
    series="default"

[menu]
  [[menu.main]]
    identifier = "fluid_acrylic"
    name = "fluid acrylic"
    url = "/categories/fluid-acrylic.html"
    weight = -100

  [[menu.main]]
    identifier = "mixed_media"
    name = "mixed media"
    url = "/categories/mixed-media.html"
    weight = -100

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact.html"
    weight = 100
