baseURL = "https://helenplatt.ca/"
languageCode = "en-us"
title = "HelenPlatt.ca"
#theme = "hugo-now-ui"

# sectionPagesMenu = "main"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"
uglyurls = true
pluralizeListTitles = false
preserveTaxonomyNames = true
paginate=36
pageinatePath="page"

[taxonomies]
  category = "categories"

[permalinks]
  post = "/:filename/"

[params]
    description = "HelenPlatt.ca Art blog and sales"
    date_format = "2006-01-02"
    tint="blue"
    background = "/img/header.png"
    series = "series"
    seriesGroup = "seriesGroup"

[menu]
  [[menu.main]]
    identifier = "gallery"
    name = "Gallery"
    url = "/"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "About Helen"
    url = "/abouthelen.html"
    weight = 10

  [[menu.main]]
    identifier = "events"
    name = "events"
    url = "/events.html"
    weight = 50

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact.html"
    weight = 100
